import { Service, GalleryItem, Testimonial } from './types';

export const SERVICES_DATA: Service[] = [
  {
    id: 'tree-removal',
    name: 'Tree Removal & Dismantling',
    category: 'Tree & Garden Care',
    description: 'Safe, controlled removal of dead, diseased, or hazardous trees. Stump rigging and complete timber disposal.',
    detailedDescription: 'Whether it is a tree posing a danger to your house, or an overgrown tree blocking natural light, we execute precise rigging and dismantling in confined gardens safely and cleanly.',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'edge-trimming',
    name: 'Edge & Lawn Trimming',
    category: 'Tree & Garden Care',
    description: 'Crisp, professional border edging and neat lawn bordering for that perfect pristine lawn finish.',
    detailedDescription: 'Define your lawns, pathways, and flowerbeds with crisp, linear lawn cuts. We keep grass strictly contained and borders beautifully kept.',
    image: 'https://images.unsplash.com/photo-1533460004989-acf010c411bb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'stump-removal',
    name: 'Stump Grinding & Removal',
    category: 'Tree & Garden Care',
    description: 'Complete removal of stubborn tree stumps below ground level, leaving the surface flat and ready.',
    detailedDescription: 'Stump removal stops unwanted tree pest infestation and prevents trip hazards. We grind stump cores and roots out cleanly so you can returf or lay paving over the space.',
    image: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'fencing',
    name: 'Premium Closeboard Fencing',
    category: 'Paving & Fencing',
    description: 'Heavy-duty closeboard, overlap, or decorative fence panels. Concrete or timber posts and gravel boards.',
    detailedDescription: 'Built to withstand rough British weather, our high-quality fencing protects your privacy and boundaries. We use pressure-treated timber, concrete posts, and master-level post digging.',
    image: 'https://images.unsplash.com/photo-1507305909242-1e76822959f9?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'flagging',
    name: 'Flagging & Patio Laying',
    category: 'Paving & Fencing',
    description: 'Indian Stone, porcelain, or standard concrete flagging for beautiful patios, pathways, and seating areas.',
    detailedDescription: 'We lay premium natural stone, Indian sandstone, and durable porcelain flags on concrete beds. Fully sub-based with hardcore layer to guarantee zero shifting or cracking over years.',
    image: 'https://images.unsplash.com/photo-1590059536219-61fe367d8b17?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'driveways',
    name: 'Block Paving & Driveways',
    category: 'Paving & Fencing',
    description: 'Hard-wearing block paved driveways or gravel surfaces built to handle heavy vehicles and last.',
    detailedDescription: 'From excavation to sand-screeding and laying block pavers. Double-bordered and weed-membrane sealed for a durable, heavy-capacity parking area with high kerb appeal.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 're-pointing',
    name: 'Brickwork Re-pointing',
    category: 'Property Maintenance',
    description: 'Restoration of crumbling mortar joints in garden walls, patios, and outdoor brick structures.',
    detailedDescription: 'Protect structural integrity from frost and water ingress. We rake out deteriorated mortar joints and apply premium heavy-duty weatherproof mix for long-lasting bounds.',
    image: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 're-grouting',
    name: 'Patio Re-grouting',
    category: 'Property Maintenance',
    description: 'Scraping and filling deteriorated joints on Indian Stone or paving to prevent weed growth.',
    detailedDescription: 'We clear out moss-ridden or empty joints and inject high-quality polymeric jointing sand or resin grout, keeping paving tiles tightly bound and completely weed-free.',
    image: 'https://images.unsplash.com/photo-1621905252507-b354bc25edac?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'jet-washing',
    name: 'Heavy Duty Jet Washing',
    category: 'Property Maintenance',
    description: 'Pressure cleaning of driveways, patios, flagging, and decking to remove grime, moss, and weeds.',
    detailedDescription: 'Restore the original colour of your paving and stones. Our industrial jet washing clears lichen, slippery slime, dirt, and heavy oil spills, followed by high-quality kiln-dried re-sanding.',
    image: 'https://images.unsplash.com/photo-1527515545081-5db817172677?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'artificial-grass',
    name: 'Realistic Artificial Grass',
    category: 'Landscaping',
    description: 'Ultra-durable, zero-maintenance fake turf. Completely child, pet, and winter-friendly.',
    detailedDescription: 'Get a clean, bright green lawn all 365 days of the year without any mowing. Complete with multi-layer sub-base drainage, weed barrier, and secure perimeter fixing.',
    image: 'https://images.unsplash.com/photo-1546483875-5f01450a876a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'digging-levelling',
    name: 'Ground Digging & Levelling',
    category: 'Landscaping',
    description: 'Excavation, soil clearance, and site levelling to prepare gardens for patios, turf, or construction.',
    detailedDescription: 'If your garden lies on an awkward slope or has rough mounds, we use compact ground machinery to level, drainage-trench, and prep your soil to perfection.',
    image: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'roof-repair',
    name: 'Roof Repairs & Maintenance',
    category: 'Property Maintenance',
    description: 'Fixing loose slate tiles, ridge tiles re-pointing, clearing gutters, and general roof maintenance.',
    detailedDescription: 'Keep your property fully leak-proof. From minor tile replacements to gutter clearances and securing lead flashing, our team ensures quick, reliable high-level maintenance.',
    image: 'https://images.unsplash.com/photo-1632829172661-419d6d3711b4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lawn-mowing',
    name: 'Regular Lawn Mowing',
    category: 'Tree & Garden Care',
    description: 'One-off or scheduled lawn mowing and clipping disposal for domestic or commercial spaces.',
    detailedDescription: 'We offer reliable, scheduled visits using professional roller lawn mowers to give your grass that striking striped aesthetic, finished with neat edge clipping.',
    image: 'https://images.unsplash.com/photo-1558904541-efa8c1a68f6a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'hedge-trimming',
    name: 'Hedge Trimming & Shaping',
    category: 'Tree & Garden Care',
    description: 'Professional cutting, reduction, and sculpting of overgrown hedges, conifers, and shrubberies.',
    detailedDescription: 'Keep your boundaries tidy, dense, and properly sized. We prune with laser-sharp alignment and bag up every single leaf and conifer clipping.',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'weeding',
    name: 'Weed Control & Clearing',
    category: 'Tree & Garden Care',
    description: 'Full weeding, clearing overgrown roots, and ecological chemical spraying to halt re-growth.',
    detailedDescription: 'We dig deep to pull weeds from root stems and lay down protective membranes or multi-action bark mulches to starve future weeds of sunlight.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'planting',
    name: 'Shrub & Flower Planting',
    category: 'Tree & Garden Care',
    description: 'Sourcing and planting seasonal flowers, trees, and shrubs that thrive in West Yorkshire soil.',
    detailedDescription: 'From beautiful borders to structural shrubs, let us suggest flowers that bloom beautifully through spring and winter and need minimal fuss.',
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'garden-turnaround',
    name: 'Full Garden Turnarounds',
    category: 'Landscaping',
    description: 'The ultimate garden makeover. Complete strip-outs, redesigns, turfs, paving, and total transformation.',
    detailedDescription: 'Overgrown jungle to designer outdoor space. We execute full turnarounds by removing old debris, levelling, laying paving, building fencing, and setting down premium turf. Our signature trade service.',
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
];

export const GALLERY_DATA: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Indian Stone Flagging Patio',
    category: 'Paving & Driveways',
    description: 'Full patio installation with premium hand-chiselled Indian Sandstone flags, jointed with dynamic resin.',
    image: 'https://images.unsplash.com/photo-1590059536219-61fe367d8b17?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gal-2',
    title: 'Bespoke Timber Closeboard Fencing',
    category: 'Fencing',
    description: 'Heavy vertical board layout on reinforced concrete corner posts and safety gravel boards in Idle, Bradford.',
    image: 'https://images.unsplash.com/photo-1507305909242-1e76822959f9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gal-3',
    title: 'Total Garden Turnaround Makeover',
    category: 'Garden Turnarounds',
    description: 'Overgrown wasteland transformed into premium artificial grass lawn, raised planting sleepers, and Indian Stone walkway.',
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gal-4',
    title: 'Perfect Block Paving Driveway',
    category: 'Paving & Driveways',
    description: 'Substantial multi-vehicle driveway paving with charcoal borders and sand-screeded foundation in Shipley.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gal-5',
    title: 'Professional Tree Removal Surgery',
    category: 'Tree Surgery & Care',
    description: 'Felling and timber rigging of dangerous 40ft conifer conjoining home boundary in Bradford.',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'gal-6',
    title: 'High-Pressure Jet Wash Before & After',
    category: 'Paving & Driveways',
    description: 'Eliminated ten years of black lichen, moss, and slippery film, finished with structural dry-kiln re-sanding.',
    image: 'https://images.unsplash.com/photo-1527515545081-5db817172677?auto=format&fit=crop&w=800&q=80',
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: 't-1',
    name: 'David Thompson',
    location: 'Wrose, Bradford',
    rating: 5,
    date: '12 May 2026',
    comment: 'The team at JS Property did an outstanding job completely turning around my back garden. They removed three huge dead tree stumps, installed secure fencing and laid Indian sandstone flags perfectly. Handled everything professionally. Highly recommended!',
    serviceCompleted: 'Full Garden Turnaround',
  },
  {
    id: 't-2',
    name: 'Sarah Mitchell',
    location: 'Baildon, Bradford',
    rating: 5,
    date: '28 April 2026',
    comment: 'Extremely reliable lads. They came out on time to quote and completed my new closeboard fencing within two days. Prompt, tidy, and no hidden costs. Outstanding trades craftsmanship.',
    serviceCompleted: 'Closeboard Fencing',
  },
  {
    id: 't-3',
    name: 'James Harrison',
    location: 'Clayton, Bradford',
    rating: 5,
    date: '02 June 2026',
    comment: 'Had my block paving driveway jet washed and re-pointed by JS. Staggering difference - looks brand new. Courteous service and very professional equipment. Will use them again for winter roof maintenance.',
    serviceCompleted: 'Jet Washing & Re-pointing',
  },
];
